// Shared brand tokens for Auto-Post auth emails.
// Body background must stay #ffffff; accents use ink/paper palette.
export const brand = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", Arial, sans-serif',
    color: '#0f0f0f',
    margin: 0,
    padding: 0,
  } as const,
  container: {
    maxWidth: '520px',
    margin: '0 auto',
    padding: '40px 32px',
  } as const,
  brandMark: {
    fontFamily: 'Fraunces, Georgia, "Times New Roman", serif',
    fontSize: '20px',
    fontWeight: 600 as const,
    letterSpacing: '-0.01em',
    color: '#0f0f0f',
    margin: '0 0 32px',
  } as const,
  h1: {
    fontFamily: 'Fraunces, Georgia, "Times New Roman", serif',
    fontSize: '30px',
    fontWeight: 500 as const,
    letterSpacing: '-0.02em',
    lineHeight: '1.15',
    color: '#0f0f0f',
    margin: '0 0 20px',
  } as const,
  text: {
    fontSize: '15px',
    color: '#3d3d3d',
    lineHeight: '1.6',
    margin: '0 0 20px',
  } as const,
  link: { color: '#0f0f0f', textDecoration: 'underline' } as const,
  button: {
    display: 'inline-block',
    backgroundColor: '#0f0f0f',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 500 as const,
    borderRadius: '6px',
    padding: '13px 22px',
    textDecoration: 'none',
    margin: '8px 0 12px',
  } as const,
  code: {
    fontFamily: '"SF Mono", Menlo, Monaco, Consolas, monospace',
    fontSize: '28px',
    fontWeight: 600 as const,
    letterSpacing: '0.15em',
    color: '#0f0f0f',
    padding: '16px 20px',
    backgroundColor: '#f5f3ee',
    borderRadius: '6px',
    display: 'inline-block',
    margin: '0 0 24px',
  } as const,
  divider: {
    border: 'none',
    borderTop: '1px solid #e8e6e0',
    margin: '32px 0 20px',
  } as const,
  footer: {
    fontSize: '12px',
    color: '#8a8880',
    lineHeight: '1.6',
    margin: '0',
  } as const,
} as const;
